# Lifesteal singleplayer/client configuration.
# Gameplay options in this file are applied only to integrated singleplayer servers.

allowGodApples: false
allowStrengthII: false
allowSwiftnessII: false
allowDebuffPotions: false
allowInstantHealingPotions: false
allowTippedArrows: false
enableEnchantmentLimits: false
allowNetheriteUpgrades: true
balancedMace: false
lockMaceRecipe: true
disableEnderPearls: false
disableCrystalPVP: false
disableTotems: false
disableBedBombing: true
nerfTntMinecarts: true
allowTNTMinecarts: false
enableRiptideCooldown: false
hideInvisPlayerKillCredit: true
maxHearts: 20
withdrawnHeartValue: 1
riptideCooldown: 200
enableCustomDiscordRpc: false
